### DISCUSSION TITLE
A card that tells me when I should start various appliances, but only when there actually is some data.

### DISCUSSION THREAD

**Discussion by AkshayRao27** [mampfes/ha_epex_spot#111] [Show and tell]
# Credit & Disclaimer
I generated most of this code using ChatGPT 4, as well as with the [Home Assistant Assistant GPT](https://chat.openai.com/g/g-HaRByhtTl-home-assistant-assistant). I'm not a programmer by any stretch of the imagination, and this post is a mix of documentation & instruction, so that when I inevitablity forget how any of this works about 2½ weeks from now, future me has something to fall back on. If you need any kind of technical help with any of the stuff below, I don't know how much I will be able to contribute ¯\\\_(ツ)\_/¯

## What this card does
- It displays when I should start my dishwasher, both in terms of time as well as in terms of the hours & minutes from now (my dishwasher only lets me set a "Start in `x` hours" timer).
- It displays when the 30° / 60° washing machine batches should end, both in terms of time as well as in terms of the hours & minutes from now (my washing machine only lets me set an "End in `x` hours" timer).
- If the time window for any of these entries have already passed, it hides that entry.
- If the time window for all of these entires has already passed, it hides the whole card.

### All Schedules:
![All Schedules](https://community-assets.home-assistant.io/original/4X/2/8/c/28c908ccedaeeec2b4bc9f807a9810a09e884a85.png)
### Only some schedules:
![image](https://github.com/mampfes/ha_epex_spot/assets/44117116/47637745-553d-4b67-aa09-d0784f35fbfd)

### 1. Install the necessary integrations
This card requires the [EPEX Spot Sensor](https://github.com/mampfes/ha_epex_spot_sensor) integration to create the entities that will feed it data, as well as [Card Tools ](https://github.com/thomasloven/lovelace-card-tools) & [Secondary Info entity Row](https://github.com/custom-cards/secondaryinfo-entity-row) for actually creating the card. All of these can be installed via HACS.

### 2. Create EPEX Spot Sensors
You need one EPEX Spot Sensor that determines the cheapest time-window for each cycle of each appliance. In my case, that meant three sensors.

After installing the integration, create a "helper" by going to Settings → Devices & Services → Helpers → Create Helper → EPEX Spot Sensor. 

My dishwasher cycle takes 3 hours & 15 minutes to run, and I don't care when the dishwasher comes on, so this is how I configured that sensor:
![Dishwasher Config Example](/images/epex-spot-sensor-dishwasher-config-example.png)

For the washing machine however, I don't want to have a batch end after 11 pm or before 5:30 am. That way I can take care of putting the laundry on the drying rack before going to bed / heading to work instead of leaving it in the washing machine to ferment like a nice Sourdough loaf. So this is how I configured the 30° / 60° Batch Sensors (with slightly different values of course):
![30deg Config Example](https://github.com/mampfes/ha_epex_spot/assets/44117116/ed222ede-5ada-4a7c-a70c-f2601ecc1ee1)

These are the three sensors that we will be extracting data from
| Appliance | Sensor (Friendly Name) | Sensor (Entity Name) |
|--|--|--|
|Dishwasher|Dishwasher: Cheapest Window|binary_sensor.dishwasher_cheapest_window|
|Washing Machine|30° Batch: Cheapest Window|binary_sensor.30deg_batch_cheapest_window|
|Washing Machine|60° Batch: Cheapest Window|binary_sensor.60deg_batch_cheapest_window|

### 3. Create Template Sensors for extracting the correct time
Once all of the EPEX Spot Sensors are set up, we need to extract either the start or the end time depending on the appliance.

Since I can only tell my dishwasher when to start, I need to know what time I should start it at.

Create a Template Sensor by going to Settings → Devices & Services → Helpers → Create Helper → Template → Template a sensor. Under "State Template", enter
```yaml
{% set future_windows = state_attr('binary_sensor.dishwasher_cheapest_window', 'data') | selectattr('start_time', 'gt', now().timestamp() | timestamp_local) | list %}
{% if future_windows %}
  {{ (strptime(future_windows[0]['start_time'], '%Y-%m-%dT%H:%M:%S%z')).strftime('%H:%M on %d/%m/%y') }}
{% else %}
  Waiting for new data
{% endif %}
```
#### WAT
Here's what's happening:
- We start by setting a variable called `future_windows` where
	 - **`state_attr('binary_sensor.dishwasher_cheapest_window', 'data')`** retrieves the data attribute from `binary_sensor.dishwasher_cheapest_window`. 
	 This data is a list of up to two entries for `start_time`
	 *(I am using smartENERGY.at which gives me data for the present day and the next day).*
	 - **`selectattr('start_time', 'gt', now().timestamp() | timestamp_local | list %)`** filters the `start_time` list and selects entries where `start_time` is greater than (`gt`) the current timestamp (`now().timestamp()`), converted to the local timezone (`| timestamp_local`). This ensures only future windows are considered. Then, `| list %` converts the filtered result back into a list (since the filtering process apparently does not return a list).
 - **`if future_windows`** is NOT empty (`%`), then
	 - **`strptime`**`(future_windows[0]['start_time'], '%Y-%m-%dT%H:%M:%S%z')` parses the `start_time` of the first (`[0]`) future window from a string, into a datetime object (`%Y-%m-%dT%H:%M:%S%z`), allowing us to then use
	 - **`strftime`**`('%H:%M on %d/%m/%y')`** to format the datetime object as we want.
 -   **`else: Waiting for new data`**: In case `future_windows` is indeed empty, that means that all of the possible `start_times` are in the past, and we need to wait for new data from the provider.

Now for the two washing machine sensors. Here, we need the`end_time` and not the `start_time`. The rest of the code is essentially the same. Here's the 30° Batch Sensor:
```yaml
{% set future_windows = state_attr('binary_sensor.30deg_batch_cheapest_window', 'data') | selectattr('end_time', 'gt', now().timestamp() | timestamp_local) | list %}
{% if future_windows %}
  {{ (strptime(future_windows[0]['end_time'], '%Y-%m-%dT%H:%M:%S%z')).strftime('%H:%M on %d/%m/%y') }}
{% else %}
  Waiting for new data
{% endif %}
```
For the 60° Batch Sensor, simply replace `binary_sensor.30deg_batch_cheapest_window` with `binary_sensor.60deg_batch_cheapest_window`
### 4. Create Template Sensors for calculating the duration
Knowing what time to start the dishwasher is one thing, but when I actually schedule it in the appliance, I need to tell it how many hours from now it should start the cycle. To calculate this, we can create another Template Sensor with this code:
```yaml
{% set future_windows = state_attr('binary_sensor.dishwasher_cheapest_window', 'data') | selectattr('start_time', 'gt', now().timestamp() | timestamp_local) | list %}
{% if future_windows %}
  {% set time_till_start = (strptime(future_windows[0]['start_time'], '%Y-%m-%dT%H:%M:%S%z') - now()).total_seconds() %}
  {{ '{:02}:{:02}'.format((time_till_start / 3600) | int, ((time_till_start % 3600) / 60) | int) }}
{% else %}
  Waiting for new data
{% endif %}
```
The first few lines are essentially the same. Here's what's happening with the additional bits:
- We parse  the `start_time` just like before using `strptime` but then also calculate the difference between the `start_time` and the current time (`now()`) in seconds, and save it in a new variable this time (`time_till_start`)
- The next line does three things:
	- It formats the hours and minutes (calculated later on in the line) to have leading zeros if necessary (using `{:02}`).
	- It divides `time_till_start` by 3600 to get the number of hours and displays the result as an integer (`| int`).
	- It divides the remainder of [time_till_start ÷ 3600] (denoted by the `%`) by 60 to get the minutes and displays the result as an integer.

Again, we do the same thing for the two washing machine sensors, but use `end_time`. Here's what the 30° Batch Sensor looks like:
```yaml
{% set future_windows = state_attr('binary_sensor.30deg_batch_cheapest_window', 'data') | selectattr('end_time', 'gt', now().timestamp() | timestamp_local) | list %}
{% if future_windows %}
  {% set next_end = (strptime(future_windows[0]['end_time'], '%Y-%m-%dT%H:%M:%S%z') - now()).total_seconds() %}
  {{ '{:02}:{:02}'.format((next_end / 3600) | int, ((next_end % 3600) / 60) | int) }}
{% else %}
  Waiting for new data
{% endif %}
```
These are the six sensors that we will use for building our card
| Appliance | Sensor (Friendly Name) | Sensor (Entity Name) |
|--|--|--|
|Dishwasher|Next Dishwasher Start (Duration)|sensor.dishwasher_start_duration|
|Dishwasher|Next Dishwasher Start (Time)|sensor.dishwasher_start_time|
|Washing Machine|Next 30° Batch End (Duration)|sensor.next_30deg_batch_end_duration|
|Washing Machine|Next 30° Batch End (Time)|sensor.next_30deg_batch_end_time|
|Washing Machine|Next 60° Batch End (Duration)|sensor.next_60deg_batch_end_duration|
|Washing Machine|Next 60° Batch End (Time)|sensor.next_60deg_batch_end_time|

## Card Code
In your dashboard, add a "Vertical Stack", select "Show Code Editor" and paste in:
```yaml
type: conditional
conditions:
  - condition: or
    conditions:
      - condition: state
        entity: sensor.dishwasher_start_duration
        state_not: Waiting for new data
      - condition: state
        entity: sensor.next_30deg_batch_end_duration
        state_not: Waiting for new data
      - condition: state
        entity: sensor.next_60deg_batch_end_duration
        state_not: Waiting for new data
card:
  type: entities
  title: Appliance Schedules
  state_color: true
  show_header_toggle: false
  entities:
    - type: conditional
      conditions:
        - entity: sensor.dishwasher_start_duration
          state_not: Waiting for new data
      row:
        entity: sensor.dishwasher_start_duration
        name: Dishwasher Start
        icon: mdi:dishwasher
        type: custom:secondaryinfo-entity-row
        secondary_info: '[[ sensor.dishwasher_start_time ]]'
    - type: conditional
      conditions:
        - entity: sensor.next_30deg_batch_end_duration
          state_not: Waiting for new data
      row:
        entity: sensor.next_30deg_batch_end_duration
        name: 30° Batch End
        icon: mdi:washing-machine
        type: custom:secondaryinfo-entity-row
        secondary_info: '[[ sensor.next_30deg_batch_end_time ]]'
    - type: conditional
      conditions:
        - entity: sensor.next_60deg_batch_end_duration
          state_not: Waiting for new data
      row:
        entity: sensor.next_60deg_batch_end_duration
        name: 60° Batch End
        icon: mdi:washing-machine
        type: custom:secondaryinfo-entity-row
        secondary_info: '[[ sensor.next_60deg_batch_end_time ]]'

```
