### DISCUSSION TITLE
Latest Start Possible to complete cycle

### DISCUSSION THREAD

**Discussion by axelfaltin** [mampfes/ha_epex_spot#186] [Q&A]
Hi Guys, 

I am trying to utilize the cheapest window to complete my cycle to heat up my water/load my battery but I I would like to push the cycle to the latest possible window not the earliest. 

Example: 
Let's assume I have cheap energy from 2-6am I and have a 1,5h cycle, I would like to start at 4:30am - right now it would start at 2 (assuming it sits after my configured earliest start) and finish at 3:30h. 

Concern:
That is not ideal as I am then consuming out of my battery during hours when power is still cheap (in the above example from 3:30 to 6:00am) as my e3dc always favours consuming own (battery) power.

How can I achieve that result?

Thanks for your support.

Axel

**Comment by mr-p666** [comment]
If you always use the cheapest four hours as a time window and you know that a cycle lasts 1 1/2 hours, then simply create a trigger at the beginning of the cheapest phase plus 2 1/2 hours.

**Reply by axelfaltin** [reply]
Firstly, thank for helping out. But adding a fixed about is tricky as the window might be shorter than 4h in total.

**Comment by mr-p666** [comment]
Of course you can also just start 1 1/2 hours before the end. 😉

**Reply by axelfaltin** [reply]
How would you do that then?

**Reply by mr-p666** [reply]
To keep it simple you could use something like this:
```
mode: single
triggers:
  - trigger: time
    at:
      entity_id: sensor.epex_end_nighttime_low_period
      offset: "-01:30:00"
actions:
  - type: turn_on
    entity_id: switch.eve_charger
    domain: switch
```
