### DISCUSSION TITLE
An Automation that pauses my connected washer-dryer till power is cheap but also offers a manual override.

### DISCUSSION THREAD

**Discussion by AkshayRao27** [mampfes/ha_epex_spot#206] [Show and tell]
# Credit & Disclaimer
I'm not a programmer by stretch of the imagination, and this post is a mix of documentation & instruction, so that when I inevitablity forget how any of this works about 2½ weeks from now, future me has something to fall back on. I had a lot of help from ChatGPT when writing this automation. If you need any kind of technical help with any of stuff below, I don't know how much I will be able to contribute ¯\\\_(ツ)\_/¯

## What this Automation does
- Unless I've manually activated an override, it pauses my washer-dryer as soon as I start it.
- It uses a service call to calculate how long the current cycle will take to complete.
- It resumes the cycle at the start of the cheapest price-window.
- It logs & notifies me throughout the whole process so that I know what's up.

## Prerequisites & Assumptions
- This automation assumes that you have an appliance that can be controlled by Home Assistant and that it has the following minimum functionality:
	- It reports its current state to HA.
	- It reports the duration of the selected cycle to HA.
	- It can be paused via HA.
	- It can be resumed via HA.
- It assumes that you want to be notified of each important step in the process, and that you want said steps to be logged in a dedicated `automation_debug.log` file.
- You don't care when the cycle starts or ends.

## Step 0: Create a separate Debug Log (Optional)
I like having all my automation debugging to be logged in a separate file and so, I created a different log file. Doing this is extremely trivial if you have the [Studio Code Server Addon](https://homeassistant.zelotes.eu/hassio/addon/a0d7b954_vscode?store=true). Start the addon and in "Explorer" click File → New Text File and call it `automation_debug.log` (if you decide on a different name, make sure you use the correct one in the automations later on).

## Step 1: Create an Input Boolean Helper
This entity will be our "override flag". When it's set, we'll be able to start the appliance immediately without waiting for it to be scheduled for the cheapest price window. This is helpful in case a cycle needs to be run urgently.

Go to Settings → Devices & Services → Helpers → Create Helper and create a "Toggle" helper. I named mine `input_boolean.aeg_washer_dryer_cheapest_window_override`. ("Toggle" helpers are coded as `input_boolean` in their entity names)

## Step 2: Create a way to specify an override.
This can be done in several ways:
- Making a dashboard card.
- Toggling it via Settings → Devices & Services → Helpers.
- Creating an automation that assigns the toggle to a physical button, etc.
I went with the third option. I have an old Z-Wave Aeotec Wallmote which I wanted to use for setting the override, so I wrote an automation:
```yaml
alias: >-
  Bathroom Wallmote: Button 1 - AEG Washer Dryer Override Resume in Cheapest
  Window
description: >-
  Allows manual override of the washer-dryer scheduling automation by pressing
  Button 1 on the Bathroom Wallmote. Automatically resets the override after the
  washer finishes its cycle so future loads are scheduled normally.
mode: single  # Prevent multiple overlapping executions of this automation

triggers:
  #🧲 Trigger 1: Wallmote Button 1 is pressed (activate override)
  #Change this whole block and specify whichever trigger is relevant to your use case.
  - device_id: af10850a69dc3f08b2e4b98f6aa56be8
    domain: zwave_js
    type: event.value_notification.central_scene
    property: scene
    property_key: "001"
    endpoint: 0
    command_class: 91
    subtype: Endpoint 0 Scene 001
    trigger: device
    value: 0
    id: Wallmote Button 1 Pressed
  #🧲 Trigger 2: Cycle ends (deactivate override)
  - trigger: state
    entity_id:
      - sensor.aeg_washer_dryer_appliancestate
    to: "Off"
    from: Running
    id: Washer Dryer changes from Running to Off

conditions: []

actions:
  - choose:
      
      # ✅ CASE 1: Wallmote Button pressed – start the next cycle immediately.
      - conditions:
          - condition: trigger
            id:
              - Wallmote Button 1 Pressed
        sequence:
           # 🔘 Activate the override input_boolean so the main automation skips scheduling
          - target:
              entity_id: input_boolean.washer_override
            action: input_boolean.turn_on
            data: {}
           # 📝 Write to automation debug log for traceability
          - data:
              level: info
              logger: automation_debug.log #If you named your log file something else in Step 0, use the correct name here.
              message: ⚠️ Override button pressed – washer will start immediately.
            action: system_log.write
          # 📱 Notify user that the override has been activated
          - data:
              title: AEG Washer Dryer
              message: >-
                ⚠️ Scheduling Override activated. The next cycle will run
                immediately.
            action: notify.mobile_app_add_your_mobile_here

       # ✅ CASE 2: Washer has finished – deactivate the override
      - conditions:
          - condition: trigger
            id:
              - Washer Dryer changes from Running to Off
        sequence:
          # 📴 Deactivate the override so next cycle will use scheduling
          - action: input_boolean.turn_off
            metadata: {}
            data: {}
            target:
              entity_id: input_boolean.aeg_washer_dryer_cheapest_window_override
          # 📝 Log the reset action
          - data:
              level: info
              logger: automation_debug.log
              message: ✅ Washer override reset after cycle completion.
            action: system_log.write
          # 📱 Notify user that the override has been reset
          - data:
              title: AEG Washer Dryer
              message: >-
                The cycle is done & the scheduling override has been reset. The
                next cycle will run when power is cheapest.
            action: notify.mobile_app_add_your_mobile_here
```
## Step 3: Create the main automation.
With the override & a way to set it in place, we can now make the automation to control the machine.
```yaml
alias: AEG Washer Dryer – Resume Cycle in Cheapest Window
description: >
  Automatically pauses the washer-dryer when it's manually started, waits until the optimal (cheapest) time window based on electricity prices, and then resumes the cycle. It can be overriden via Button 1 on the Bathroom-Wallmote.
mode: single # Prevent multiple overlapping executions of this automation

trigger:
  # This automation is triggered when the appliance is manually started.
  # It listens for the appliance state changing from "Ready To Start" to "Running"
  - platform: state
    entity_id: sensor.aeg_washer_dryer_appliancestate
    from: Ready To Start
    to: Running
    id: Washer dryer changes from Ready To Start to Running

condition: []

action:
  - choose:
      # 🧨 CASE 1: Override is active – skip scheduling logic
      - conditions:
          - condition: state
            entity_id: input_boolean.aeg_washer_dryer_cheapest_window_override
            state: "on"
        # Create an entry in "automation_debug.log" for traceability.
        sequence:
          - service: system_log.write
            data:
              level: info
              logger: automation_debug.log
              message: "🚫 Washer-dryer scheduling skipped due to override."
      # ✅ CASE 2: No override – continue with optimal time scheduling
      - conditions:
          - condition: state
            entity_id: input_boolean.aeg_washer_dryer_cheapest_window_override
            state: "off"
        sequence:
          # 🕐 Short delay to ensure the appliance state has updated
          - delay:
              seconds: 1

          # ⏸️ Pause the washer to prevent it from washing further
          - service: button.press
            target:
              entity_id: button.aeg_washer_dryer_executecommand_3

          # 🔌 Call the EPEX Spot service to get the cheapest time slot that fits the program's estimated runtime
          - service: epex_spot.get_lowest_price_interval
            data:
              device_id: 586b828bc8000a04c65aec0c9cc76503 #Use the relevant EPEX Spot Device ID here.
              duration:
                hours: 0
                minutes: "{{ states('sensor.aeg_washer_dryer_timetoend') | int }}"
                seconds: 0
            response_variable: cheapest_window

          # ⏳ Wait until a valid response has been received from the EPEX service
          - wait_template: >
              {{ cheapest_window is defined and as_timestamp(cheapest_window.start) | int > 0 }}
            timeout: "00:10:00"
            continue_on_timeout: false

          # 🧾 Log the selected time window and price to the automation_debug.log
          - service: system_log.write
            data:
              level: info
              logger: automation_debug.log
              message: >
                🧼 Cheapest EPEX window acquired:
                Start: {{ cheapest_window.start }},
                End: {{ cheapest_window.end }},
                Net Price: {{ cheapest_window.net_price_per_kwh }} €/kWh

          # 📱 Notify the user via mobile app when the washer is scheduled
          # Format the time for human readability: show only "HH:MM" or "tomorrow at HH:MM"
          - service: notify.mobile_app_add_your_mobile_here
            data:
              title: AEG Washer Dryer
              message: >
                {% set start = cheapest_window.start %}
                {% set end = cheapest_window.end %}
                {% set now_ts = now().date() %}
                {% set start_ts = start.date() %}
                {% set end_ts = end.date() %}
                {% set start_text = "tomorrow at " ~ start.strftime('%H:%M') if start_ts > now_ts else start.strftime('%H:%M') %}
                {% set end_text = "tomorrow at " ~ end.strftime('%H:%M') if end_ts > now_ts else end.strftime('%H:%M') %}
                🧼 Washer-dryer will start {{ start_text }} and run until {{ end_text }}.
                Scheduled based on lowest electricity rate ({{ cheapest_window.net_price_per_kwh }} €/kWh).

          # ⏲️ Wait until the calculated cheapest start time arrives
          - delay:
              seconds: >
                {% set wait = as_timestamp(cheapest_window.start) - as_timestamp(now()) %}
                {{ [wait, 0] | max | int }}

          # ▶️ Log that the washer is starting now
          - service: system_log.write
            data:
              level: info
              logger: automation_debug.log
              message: >
                ▶️ Starting washer-dryer now at {{ now() }} (Scheduled: {{ cheapest_window.start }})

          # 📱 Notify the user that the cycle is now starting
          - service: notify.mobile_app_add_your_mobile_here
            data:
              title: AEG Washer Dryer
              message: >
                ▶️ Washer-dryer is starting now ({{ now().strftime('%H:%M') }}).

          # ▶️ Resume the washer's paused cycle
          - service: button.press
            target:
              entity_id: button.aeg_washer_dryer_executecommand_4
```

### Assumptions
This code assumes that:
- You are using smartENERGY.at as your provider.
- The entity name that reports the cycle duration is `sensor.aeg_washer_dryer_timetoend`. 
- `sensor.aeg_washer_dryer_timetoend` reports the number of minutes.
- There is no appreciable lag in the communication between HA & the Appliance.
