### DISCUSSION TITLE
Highest hour - directly as time to be used in automation

### DISCUSSION THREAD

**Discussion by riesi77** [mampfes/ha_epex_spot#38] [Show and tell]
Hi,

I adopted the low sensor demo code a bit to a) show me the highest price (I want to get a push notification then) and b) directly output a timestamp so it can be used in time based automations (using the UI for automations). 
The sensor looks like this:

```
- name: epex_start_high_period_1h
        device_class: timestamp
        state: >- 
          {% set ns = namespace(attr_dict=[]) %}
          {% for item in (state_attr('sensor.epex_spot_at_price', 'data'))[0:24] %}
              {%- set ns.attr_dict = ns.attr_dict + [(loop.index-1,item["price_eur_per_mwh"])] %}
          {% endfor %}
          {%- set price_map = dict(ns.attr_dict) %}
          {%- set price_sort = price_map.values()|list %}
          {%- set keys_list = price_map.keys()|list %}
          {%- set ns = namespace(combo=[]) %}
          {%- for p in keys_list %}
            {%- set p = p|int %}
            {%- if p < 22 %}
              {%- set ns.combo = ns.combo + [(p, ((price_sort)[p]  )|round(2))] %}
            {%- endif %}
          {%- endfor %}
          {%- set mapper = dict(ns.combo) %}
          {%- set key = mapper.keys()|list %}
          {%- set val = mapper.values()|list %}
          {%- set val_max = mapper.values()|max %}
          {%- set hour = key[val.index(val_max)] | string %}
          {{today_at(hour+":00") }}
```

The automation like this. It uses pushover to deliver my notification:

```
alias: "Awattar most expensive hour starts"
description: ""
trigger:
  - platform: time
    at: sensor.epex_start_high_period_1h
condition: []
action:
  - service: notify.pushover
    data:
      message: >-
        Strompreis: Teuerste Stunde ({{
        states('sensor.epex_spot_at_highest_price') }} Cent) startet jetzt ({{
        now().strftime('%H:%M') }})
mode: single
```

![image](https://github.com/mampfes/ha_epex_spot/assets/67387975/724ba164-cc41-4291-979b-cc70e4e9acb1)

**Comment by mampfes** [comment]
Just to be curios: Wouldn't the rank sensor together with the following automation do the same?

```
trigger:
  - platform: state
    entity_id:
      - sensor.epex_spot_de_rank
condition:
  - condition: numeric_state
    entity_id: sensor.epex_spot_de_rank
    above: 22
action: []
```

**Reply by riesi77** [reply]
you are fullyright and it's a very elegant solution.
However I see one tiny advantage of having the timestamp: You can see when it will start:

![image](https://github.com/mampfes/ha_epex_spot/assets/67387975/d8ee7eba-6ac1-4ce5-b538-9f72a2905347)

**Comment by riesi77** [comment]
Another questino, mampfes: How would you turn off the device after the hour is over?
I can just imagine having another timestamp sensor that basically has starttime + 1h and create a second automation for turning the device off. But maybe you have a more elegant solution?

**Reply by mr-p666** [reply]
You can just use a delay in your action section:
```
action:
  - type: turn_on
    device_id: 5921b941538f23da8a21cbf29626a3ab
    entity_id: f25613067c63fdf9c9d178b058c0c822
    domain: switch
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: 5921b941538f23da8a21cbf29626a3ab
    entity_id: f25613067c63fdf9c9d178b058c0c822
    domain: switch
mode: single
```
