### DISCUSSION TITLE
Color prices based on median in diagram

### DISCUSSION THREAD

**Discussion by riesi77** [mampfes/ha_epex_spot#42] [Show and tell]
I tweakted the diagram with the prices a bit to indicate prices below the median with green and above with red. 
The trick was to use a config-template-card (https://github.com/iantrich/config-template-card) in order to bring in sensor values into the color definition:

![image](https://github.com/mampfes/ha_epex_spot/assets/67387975/a75be328-1500-4612-9b64-db260a785e20)

```
type: custom:config-template-card
entities:
  - sensor.epex_spot_at_price
variables:
  MEDIAN: states['sensor.epex_spot_at_median_price']
card:
  type: custom:apexcharts-card
  header:
    show: true
    title: Strompreise
    show_states: true
    colorize_states: true
  graph_span: 24h
  span:
    start: day
  now:
    show: true
    label: Now
  experimental:
    color_threshold: true
    hidden_by_default: false
  series:
    - entity: sensor.epex_spot_at_price
      name: Aktueller Preis
      color: white
      show:
        legend_value: false
        in_header: true
        in_chart: false
    - entity: sensor.epex_spot_at_median_price
      name: Median
      color: orange
      show:
        legend_value: false
        in_header: true
        in_chart: false
    - entity: sensor.epex_spot_at_highest_price
      name: Höchster Preis
      color: red
      show:
        legend_value: false
        in_header: true
        in_chart: false
    - entity: sensor.epex_spot_at_price
      name: Electricity Price
      show:
        legend_value: false
        in_header: false
        in_chart: true
      type: column
      extend_to: end
      color_threshold:
        - value: 0
          color: green
        - value: ${MEDIAN.state * 1}
          color: red
      data_generator: >
        return entity.attributes.data.map((entry, index) => { return [new
        Date(entry.start_time).getTime(), entry.price_eur_per_mwh ]; });

```

I did even one step further - pretty sure there would be a way to solve this within the card definition, but I'm no HA expert: I created a template sensor that contains "red" or "green" depending on the current price - and I use that sensor to color the price in the card header:

```
      - name: "Strompreis Farbe"
        unique_id: "epex_spot_color"
        state: >
          {% if (states('sensor.epex_spot_at_price') | float <= states('sensor.epex_spot_at_median_price') | float) -%}
           green
          {%- else -%}
           red
          {%- endif %}
```
Above code needs to go into configuration.yaml file

Then, you can use the sensor to extend the card configuration:

```
type: custom:config-template-card
entities:
  - sensor.epex_spot_at_price
variables:
  MEDIAN: states['sensor.epex_spot_at_median_price']
  col1: states['sensor.strompreis_farbe'].state
card:
  type: custom:apexcharts-card
  header:
    show: true
    title: Strompreise
    show_states: true
    colorize_states: true
  graph_span: 24h
  span:
    start: day
  now:
    show: true
    label: Now
  experimental:
    color_threshold: true
    hidden_by_default: false
  series:
    - entity: sensor.epex_spot_at_price
      name: Aktueller Preis
      color: ${col1}
      show:
        legend_value: false
        in_header: true
        in_chart: false
    - entity: sensor.epex_spot_at_median_price
      name: Median
      color: orange
      show:
        legend_value: false
        in_header: true
        in_chart: false
    - entity: sensor.epex_spot_at_highest_price
      name: Höchster Preis
      color: red
      show:
        legend_value: false
        in_header: true
        in_chart: false
    - entity: sensor.epex_spot_at_price
      name: Electricity Price
      show:
        legend_value: false
        in_header: false
        in_chart: true
      type: column
      extend_to: end
      color_threshold:
        - value: 0
          color: green
        - value: ${MEDIAN.state * 1}
          color: red
      data_generator: >
        return entity.attributes.data.map((entry, index) => { return [new
        Date(entry.start_time).getTime(), entry.price_eur_per_mwh ]; });
```

And voila, you also have the price in the header colored.
![image](https://github.com/mampfes/ha_epex_spot/assets/67387975/04bcca94-689c-44d3-a6c9-8415193c2fba)

**Comment by aichingerk** [comment]
Hi riesi77,
I kept it simple so that you can also operate the graph with your finger on the tablet. You can scroll from the bottom left to the bottom right. I have enabled the colour differences through the experiment mode, so you can also click on individual bars and you can see something on the tab.


![image](https://github.com/mampfes/ha_epex_spot/assets/82718567/41cf3de3-d528-4b28-a977-4f8f004b0a89)

You can see the code here:
```
type: custom:apexcharts-card
header:
  show: true
  title: Strompreis über den Tag
all_series_config:
  stroke_width: 5
  type: line
  unit: ct/kWh
graph_span: 48h
span:
  start: day
now:
  show: true
  label: Now
  color: var(--primary-color)
series:
  - entity: sensor.epex_spot_at_net_price
    yaxis_id: uurprijs
    stroke_width: 10
    float_precision: 2
    type: column
    extend_to: end
    show:
      extremas: true
    data_generator: >
      return entity.attributes.data.map((entry, index) => { return [new
      Date(entry.start_time).getTime(), entry.price_ct_per_kwh]; });  
    color_threshold:
      - value: 1
        color: '#0080FF'
      - value: 5
        color: '#00FFFF'
      - value: 15
        color: '#00FF00'
      - value: 19
        color: '#FF8000'
      - value: 25
        color: '#FF0000'
experimental:
  color_threshold: true
yaxis:
  - id: uurprijs
    apex_config:
      title:
        text: ct/kWh
      tickAmount: 12
apex_config:
  legend:
    show: false
  tooltip:
    style:
      fontSize: 17px
    x:
      show: true
      format: HH:00 - HH:59
```
