### DISCUSSION TITLE
Could you add an update service to be called with automation at specific times?

### DISCUSSION THREAD

**Discussion by deltamelter** [mampfes/ha_epex_spot#52] [Q&A] [answered]
GB-30 is great addition.  Currently I have to manually reload the service or wait for the next refresh.
GB-60 updates same time every day (09:30 BST) and GB-30 updates at 15:45, so would be nice to just add those times in an automation to force refresh.

![image](https://github.com/mampfes/ha_epex_spot/assets/27061628/4c451940-1235-4af6-ba42-337f17ab0d7f)

Here is an example where I use automation to force refresh a solcast service at a specific time
![image](https://github.com/mampfes/ha_epex_spot/assets/27061628/fad86fe8-c3b4-4a5e-9638-c4d4659ee5b2)

**Comment by mampfes** [comment]
fixed by #55 

Note: This will be available with release 2.1.0

**Reply by deltamelter** [reply]
That's great, thanks.  will take a look.

**Reply by deltamelter** [reply]
Choosing the correct device is not easy...
![image](https://github.com/mampfes/ha_epex_spot/assets/27061628/9c9e7213-ffbc-4ce6-bb92-9542bea9695b)
I wonder if there are options for changing the naming as it is currently quite confusing...
![image](https://github.com/mampfes/ha_epex_spot/assets/27061628/fe401be0-0f5f-4013-9270-6a4e01486e7e)

**Reply by deltamelter** [reply]
Maybe I misunderstood how this has been implemented, but the automation fired and did not update either service/device
![image](https://github.com/mampfes/ha_epex_spot/assets/27061628/5a47c531-fac4-4370-a883-52030e39ae84)

"Reload" on configure menu fetched the data instantly

**Comment by mampfes** [comment]
Oh, thanks. Please try the latest main branch. I added a fix, but wasn't able to test it so far.

**Reply by mstu01** [reply]
@mampfes Seems not to be fixed - at least not with the version 2.1.0 via HACS. Reloading the configuration updates instant.

**Comment by deltamelter** [comment, marked as answer]
> Oh, thanks. Please try the latest main branch. I added a fix, but wasn't able to test it so far.

Yes, works well.  I put 2 times on this time, first one (15:45:00) was too early, the next (15:45:45) updated all the graphs and data instantly like when pressing reload under "Configure".
Thanks

**Reply by deltamelter** [reply]
@mampfes This seems to have stopped working again.  Is there anything I can debug?
Can you think of any reason this would just stop working?

**Reply by mampfes** [reply]
Did you check the log? Is your trigger still active?

**Reply by deltamelter** [reply]
nothing in system log.
I logbook, shows the automation triggering only...
The trigger is active yes.
I have 2 different instances, one for original GB60, then added another for GB30.  Don't know if this is the correct way to add both, but as shown in screenshot on October 25th.
I added both "services" and All devices, as follows:
The automation runs, and originally caused the the graphs, etc to update straight away but it stopped.  
I run HA as a docker but haven't updated since september

```
alias: reload epex?
description: ""
trigger:
  - platform: time
    at: "15:45:00"
  - platform: time
    at: "15:45:45"
  - platform: time
    at: "15:51:45"
  - platform: time
    at: "09:30:00"
  - platform: time
    at: "09:30:45"
  - platform: time
    at: "09:34:00"
  - platform: time
    at: "09:33:00"
  - platform: time
    at: "09:31:00"
  - platform: time
    at: "09:32:00"
  - platform: time
    at: "09:33:00"
  - platform: time
    at: "20:08:00"
condition: []
action:
  - service: epex_spot.fetch_data
    data:
      device_id: fd5a0a78bf243ee26fa33f57d5ce7f83
  - service: epex_spot.fetch_data
    data:
      device_id: 59634995300179b14c5017173671c8eb
  - service: epex_spot.fetch_data
    data: {}
mode: single
```
