### DISCUSSION TITLE
Virtual switch for lowest and highest price period

### DISCUSSION THREAD

**Discussion by mr-p666** [mampfes/ha_epex_spot#56] [Ideas]
Hej folks,

I'm looking for a way to check whether I'm still in the lowest or highest price period.
One reason for this is to stop consumption as soon as the period is up - without requiring a "delay" in any of my automations, and the other is to decide whether I will stop them at the end of the period, when my PV still harvests enough.

I'm not sure if this is something that should and could be done with this integration or can be done in another way (better), but all the possibilities outside of this integration mean always making changes at multiple points rather than just one.

Therefore, I would like to start a discussion about how best to integrate such a trigger.

**Comment by mr-p666** [comment]
Hey again,
either I'm alone with this problem or I'm the only one who can't see the forest for the trees. :smile:

I looked through the readme again and found that the service call response should output something like this, which contains everything I'm looking for:
```
Start: “2023-09-29T12:00:00+00:00”
End: “2023-09-29T13:00:00+00:00”
price_eur_per_mwh: 77.04
price_ct_per_kwh: 7.704000000000001
Net price_ct_per_kwh: 23.6394928
```
But with the current examples I only ever get the start times.
@mampfes Can you give me a hint or expand the documentation on what exactly to do to achieve this output?
Thank you! :smile:

**Comment by mampfes** [comment]
Hi, you can setup 2 template sensors, one for the start time and one for the end time - both using the same arguments for the Epex Spot service call. With this 2 sensors, your automation should be feasible, or?

**Comment by mr-p666** [comment]
Great scott...
I don't know why but I always tried 'stop' instead of 'end' and wondered why it didn't work. :worried: 
```
- trigger:
    - platform: time
      at: "20:30:00"
    - platform: homeassistant
      event: start
  action:
    - service: epex_spot.get_lowest_price_interval
      data:
        earliest_start: "22:00:00"
        duration:
          hours: 3
          minutes: 15
      response_variable: resp
  sensor:
    - name: "EPEX End 26h Low Period"
      device_class: timestamp
      state: "{{ resp.end is defined and resp.end }}"
```
So this does exactly what I was looking for. Just too many trees. :wink:
