### ISSUE TITLE
Data for next 24 hrs

### ISSUE THREAD

**Issue by smitterer** [mampfes/ha_epex_spot#1]
Hi!

Thanks for creating this module.

I'm currently pulling the data via Awattar API using Node-Red but am not able to get the prices for all upcoming next 24 hours.

From my knowledge, Awattar only publishes the data something about 14:00 UTC+1.

Did you find a way to receive the prices for the upcoming 24hrs, no matter at which time you pull them?

In the sensor data, I can only see the prices for today.

Thanks

**Comment by mampfes** [comment]
Hi, I'm not sure if I understand your question correctly. This module fetches all available data, which contains the prices to today and after 14:oo also the prices for tomorrow:

```
unit_of_measurement: EUR/MWh
icon: mdi:currency-eur
friendly_name: EPEX Spot de Price
data:
  - start_time: '2023-01-02T00:00:00+00:00'
    end_time: '2023-01-02T01:00:00+00:00'
    price_eur_per_mwh: 51.67
  - start_time: '2023-01-02T01:00:00+00:00'
    end_time: '2023-01-02T02:00:00+00:00'
    price_eur_per_mwh: 52.93
  - start_time: '2023-01-02T02:00:00+00:00'
    end_time: '2023-01-02T03:00:00+00:00'
    price_eur_per_mwh: 44.09
  - start_time: '2023-01-02T03:00:00+00:00'
    end_time: '2023-01-02T04:00:00+00:00'
    price_eur_per_mwh: 50.08
  - start_time: '2023-01-02T04:00:00+00:00'
    end_time: '2023-01-02T05:00:00+00:00'
    price_eur_per_mwh: 69.72
  - start_time: '2023-01-02T05:00:00+00:00'
    end_time: '2023-01-02T06:00:00+00:00'
    price_eur_per_mwh: 105.08
  - start_time: '2023-01-02T06:00:00+00:00'
    end_time: '2023-01-02T07:00:00+00:00'
    price_eur_per_mwh: 140.64
  - start_time: '2023-01-02T07:00:00+00:00'
    end_time: '2023-01-02T08:00:00+00:00'
    price_eur_per_mwh: 145.98
  - start_time: '2023-01-02T08:00:00+00:00'
    end_time: '2023-01-02T09:00:00+00:00'
    price_eur_per_mwh: 147.05
  - start_time: '2023-01-02T09:00:00+00:00'
    end_time: '2023-01-02T10:00:00+00:00'
    price_eur_per_mwh: 145.61
  - start_time: '2023-01-02T10:00:00+00:00'
    end_time: '2023-01-02T11:00:00+00:00'
    price_eur_per_mwh: 143.35
  - start_time: '2023-01-02T11:00:00+00:00'
    end_time: '2023-01-02T12:00:00+00:00'
    price_eur_per_mwh: 144.38
  - start_time: '2023-01-02T12:00:00+00:00'
    end_time: '2023-01-02T13:00:00+00:00'
    price_eur_per_mwh: 143.76
  - start_time: '2023-01-02T13:00:00+00:00'
    end_time: '2023-01-02T14:00:00+00:00'
    price_eur_per_mwh: 148.2
  - start_time: '2023-01-02T14:00:00+00:00'
    end_time: '2023-01-02T15:00:00+00:00'
    price_eur_per_mwh: 155.34
  - start_time: '2023-01-02T15:00:00+00:00'
    end_time: '2023-01-02T16:00:00+00:00'
    price_eur_per_mwh: 162.89
  - start_time: '2023-01-02T16:00:00+00:00'
    end_time: '2023-01-02T17:00:00+00:00'
    price_eur_per_mwh: 170
  - start_time: '2023-01-02T17:00:00+00:00'
    end_time: '2023-01-02T18:00:00+00:00'
    price_eur_per_mwh: 174.74
  - start_time: '2023-01-02T18:00:00+00:00'
    end_time: '2023-01-02T19:00:00+00:00'
    price_eur_per_mwh: 164.46
  - start_time: '2023-01-02T19:00:00+00:00'
    end_time: '2023-01-02T20:00:00+00:00'
    price_eur_per_mwh: 153
  - start_time: '2023-01-02T20:00:00+00:00'
    end_time: '2023-01-02T21:00:00+00:00'
    price_eur_per_mwh: 141.67
  - start_time: '2023-01-02T21:00:00+00:00'
    end_time: '2023-01-02T22:00:00+00:00'
    price_eur_per_mwh: 134.91
  - start_time: '2023-01-02T22:00:00+00:00'
    end_time: '2023-01-02T23:00:00+00:00'
    price_eur_per_mwh: 124.22
  - start_time: '2023-01-02T23:00:00+00:00'
    end_time: '2023-01-03T00:00:00+00:00'
    price_eur_per_mwh: 130.01
  - start_time: '2023-01-03T00:00:00+00:00'
    end_time: '2023-01-03T01:00:00+00:00'
    price_eur_per_mwh: 120
  - start_time: '2023-01-03T01:00:00+00:00'
    end_time: '2023-01-03T02:00:00+00:00'
    price_eur_per_mwh: 118.76
  - start_time: '2023-01-03T02:00:00+00:00'
    end_time: '2023-01-03T03:00:00+00:00'
    price_eur_per_mwh: 115
  - start_time: '2023-01-03T03:00:00+00:00'
    end_time: '2023-01-03T04:00:00+00:00'
    price_eur_per_mwh: 113.63
  - start_time: '2023-01-03T04:00:00+00:00'
    end_time: '2023-01-03T05:00:00+00:00'
    price_eur_per_mwh: 116.27
  - start_time: '2023-01-03T05:00:00+00:00'
    end_time: '2023-01-03T06:00:00+00:00'
    price_eur_per_mwh: 138.92
  - start_time: '2023-01-03T06:00:00+00:00'
    end_time: '2023-01-03T07:00:00+00:00'
    price_eur_per_mwh: 159.92
  - start_time: '2023-01-03T07:00:00+00:00'
    end_time: '2023-01-03T08:00:00+00:00'
    price_eur_per_mwh: 169.17
  - start_time: '2023-01-03T08:00:00+00:00'
    end_time: '2023-01-03T09:00:00+00:00'
    price_eur_per_mwh: 171.18
  - start_time: '2023-01-03T09:00:00+00:00'
    end_time: '2023-01-03T10:00:00+00:00'
    price_eur_per_mwh: 168.57
  - start_time: '2023-01-03T10:00:00+00:00'
    end_time: '2023-01-03T11:00:00+00:00'
    price_eur_per_mwh: 169.49
  - start_time: '2023-01-03T11:00:00+00:00'
    end_time: '2023-01-03T12:00:00+00:00'
    price_eur_per_mwh: 164.5
  - start_time: '2023-01-03T12:00:00+00:00'
    end_time: '2023-01-03T13:00:00+00:00'
    price_eur_per_mwh: 160.91
  - start_time: '2023-01-03T13:00:00+00:00'
    end_time: '2023-01-03T14:00:00+00:00'
    price_eur_per_mwh: 163.06
  - start_time: '2023-01-03T14:00:00+00:00'
    end_time: '2023-01-03T15:00:00+00:00'
    price_eur_per_mwh: 167.73
  - start_time: '2023-01-03T15:00:00+00:00'
    end_time: '2023-01-03T16:00:00+00:00'
    price_eur_per_mwh: 166.61
  - start_time: '2023-01-03T16:00:00+00:00'
    end_time: '2023-01-03T17:00:00+00:00'
    price_eur_per_mwh: 170.72
  - start_time: '2023-01-03T17:00:00+00:00'
    end_time: '2023-01-03T18:00:00+00:00'
    price_eur_per_mwh: 168.93
  - start_time: '2023-01-03T18:00:00+00:00'
    end_time: '2023-01-03T19:00:00+00:00'
    price_eur_per_mwh: 160.99
  - start_time: '2023-01-03T19:00:00+00:00'
    end_time: '2023-01-03T20:00:00+00:00'
    price_eur_per_mwh: 149.62
  - start_time: '2023-01-03T20:00:00+00:00'
    end_time: '2023-01-03T21:00:00+00:00'
    price_eur_per_mwh: 130.99
  - start_time: '2023-01-03T21:00:00+00:00'
    end_time: '2023-01-03T22:00:00+00:00'
    price_eur_per_mwh: 114.27
  - start_time: '2023-01-03T22:00:00+00:00'
    end_time: '2023-01-03T23:00:00+00:00'
    price_eur_per_mwh: 93.66
```
