### ISSUE TITLE
template

### ISSUE THREAD

**Issue by clarenze666** [mampfes/ha_epex_spot#106]
I was trying to modify the proposed template so that it will also activate the heating when no epex data is available.
I tried the following:
```
    sensor:
      - name: "EPEX Start 24h Low Period"
        device_class: timestamp
        state: "{{ resp.start if resp.start is defined else (today_at("03:00") + timedelta(days=1)) }}"
```
But home-assistant does not buy it. The error message does not help. What did I make wrong? I can't figure it out.

**Comment by clarenze666** [comment]
> I was trying to modify the proposed template so that it will also activate the heating when no epex data is available. I tried the following:
> 
> ```
>     sensor:
>       - name: "EPEX Start 24h Low Period"
>         device_class: timestamp
>         state: "{{ resp.start if resp.start is defined else (today_at("03:00") + timedelta(days=1)) }}"
> ```
> 
> But home-assistant does not buy it. The error message does not help. What did I make wrong? I can't figure it out.

I finally figured it out: I have to use single quotes.
```
    sensor:
      - name: "EPEX Start 24h Low Period"
        device_class: timestamp
        state: "{{ resp.start if resp.start is defined else (today_at('03:00') + timedelta(days=1)) }}"
```

Any ideas how I can test it? I.e. how can I simulate that epex does not get any data?
