### ISSUE TITLE
Make get_lowest_price_interval display the correct time(zone)

### ISSUE THREAD

**Issue by gigatexel** [mampfes/ha_epex_spot#109]
When I run this service call

```
service: epex_spot.get_lowest_price_interval
data:
  device_id: c93a744932f7362542a3e1bde3361580
  duration:
    hours: 3
    minutes: 0
    seconds: 0
```

I get this response
```
start: "2024-02-19T12:00:00+00:00"
end: "2024-02-19T15:00:00+00:00"
price_eur_per_mwh: 55.55
price_ct_per_kwh: 5.555
net_price_ct_per_kwh: 5.555
```

However, it is clear that the 13-16h interval is the cheapest.
 ```
state_class: measurement
data: 
- start_time: '2024-02-19T00:00:00+01:00'
  end_time: '2024-02-19T01:00:00+01:00'
  price_eur_per_mwh: 44
  price_ct_per_kwh: 4.4
- start_time: '2024-02-19T01:00:00+01:00'
  end_time: '2024-02-19T02:00:00+01:00'
  price_eur_per_mwh: 44.84
  price_ct_per_kwh: 4.484
- start_time: '2024-02-19T02:00:00+01:00'
  end_time: '2024-02-19T03:00:00+01:00'
  price_eur_per_mwh: 44.79
  price_ct_per_kwh: 4.479
- start_time: '2024-02-19T03:00:00+01:00'
  end_time: '2024-02-19T04:00:00+01:00'
  price_eur_per_mwh: 43.91
  price_ct_per_kwh: 4.391
- start_time: '2024-02-19T04:00:00+01:00'
  end_time: '2024-02-19T05:00:00+01:00'
  price_eur_per_mwh: 44.92
  price_ct_per_kwh: 4.492
- start_time: '2024-02-19T05:00:00+01:00'
  end_time: '2024-02-19T06:00:00+01:00'
  price_eur_per_mwh: 51.57
  price_ct_per_kwh: 5.157
- start_time: '2024-02-19T06:00:00+01:00'
  end_time: '2024-02-19T07:00:00+01:00'
  price_eur_per_mwh: 68.71
  price_ct_per_kwh: 6.871
- start_time: '2024-02-19T07:00:00+01:00'
  end_time: '2024-02-19T08:00:00+01:00'
  price_eur_per_mwh: 79.17
  price_ct_per_kwh: 7.917
- start_time: '2024-02-19T08:00:00+01:00'
  end_time: '2024-02-19T09:00:00+01:00'
  price_eur_per_mwh: 83.9
  price_ct_per_kwh: 8.39
- start_time: '2024-02-19T09:00:00+01:00'
  end_time: '2024-02-19T10:00:00+01:00'
  price_eur_per_mwh: 75.08
  price_ct_per_kwh: 7.508
- start_time: '2024-02-19T10:00:00+01:00'
  end_time: '2024-02-19T11:00:00+01:00'
  price_eur_per_mwh: 70.93
  price_ct_per_kwh: 7.093
- start_time: '2024-02-19T11:00:00+01:00'
  end_time: '2024-02-19T12:00:00+01:00'
  price_eur_per_mwh: 69.3
  price_ct_per_kwh: 6.93
- start_time: '2024-02-19T12:00:00+01:00'
  end_time: '2024-02-19T13:00:00+01:00'
  price_eur_per_mwh: 61.28
  price_ct_per_kwh: 6.128
- start_time: '2024-02-19T13:00:00+01:00'
  end_time: '2024-02-19T14:00:00+01:00'
  price_eur_per_mwh: 54.84
  price_ct_per_kwh: 5.484
- start_time: '2024-02-19T14:00:00+01:00'
  end_time: '2024-02-19T15:00:00+01:00'
  price_eur_per_mwh: 54.68
  price_ct_per_kwh: 5.468
- start_time: '2024-02-19T15:00:00+01:00'
  end_time: '2024-02-19T16:00:00+01:00'
  price_eur_per_mwh: 57.14
  price_ct_per_kwh: 5.714
- start_time: '2024-02-19T16:00:00+01:00'
  end_time: '2024-02-19T17:00:00+01:00'
  price_eur_per_mwh: 62.91
  price_ct_per_kwh: 6.291
- start_time: '2024-02-19T17:00:00+01:00'
  end_time: '2024-02-19T18:00:00+01:00'
  price_eur_per_mwh: 72.04
  price_ct_per_kwh: 7.204
- start_time: '2024-02-19T18:00:00+01:00'
  end_time: '2024-02-19T19:00:00+01:00'
  price_eur_per_mwh: 97.54
  price_ct_per_kwh: 9.754
- start_time: '2024-02-19T19:00:00+01:00'
  end_time: '2024-02-19T20:00:00+01:00'
  price_eur_per_mwh: 80.07
  price_ct_per_kwh: 8.007
- start_time: '2024-02-19T20:00:00+01:00'
  end_time: '2024-02-19T21:00:00+01:00'
  price_eur_per_mwh: 72.04
  price_ct_per_kwh: 7.204
- start_time: '2024-02-19T21:00:00+01:00'
  end_time: '2024-02-19T22:00:00+01:00'
  price_eur_per_mwh: 67.51
  price_ct_per_kwh: 6.751
- start_time: '2024-02-19T22:00:00+01:00'
  end_time: '2024-02-19T23:00:00+01:00'
  price_eur_per_mwh: 66.27
  price_ct_per_kwh: 6.627
- start_time: '2024-02-19T23:00:00+01:00'
  end_time: '2024-02-20T00:00:00+01:00'
  price_eur_per_mwh: 59.07
  price_ct_per_kwh: 5.907

price_ct_per_kwh: 7.508
unit_of_measurement: EUR/MWh
icon: mdi:currency-eur
friendly_name: EPEX Spot Data Price
```
