### ISSUE TITLE
Different service call results depending on where the service is called.

### ISSUE THREAD

**Issue by gigatexel** [mampfes/ha_epex_spot#117]
I'm trying to determine the start of the lowest price interval, based on the `epex_spot.get_lowest_price_interval` service call.

If I use this service call in the Developers tools:
```
service: epex_spot.get_lowest_price_interval
data:
  duration:
    hours: 3
  earliest_start: "07:00:00"
  latest_end: "16:00:00"
```

I get this response:
```
start: "2024-03-29T12:00:00+01:00"
end: "2024-03-29T15:00:00+01:00"
price_eur_per_mwh: 12.09
price_ct_per_kwh: 1.209
net_price_ct_per_kwh: 1.209

```

12:00 in localized time is correct!

But when I use the service call like this, in the config-file:
```
  - trigger:
      - platform: time
        at: 00:00:01
    action:
      - service: epex_spot.get_lowest_price_interval
        data:
          duration:
            hours: 2
          earliest_start: "07:00:00"
          latest_end: "16:00:00"
        response_variable: resp
    sensor:
      - name: start_laagste_prijs
        device_class: timestamp
        state: "{{ resp.start is defined and resp.start }}"
```
Then the `sensor.start_laagste_prijs` gets a different value, that is wrong.

![image](https://github.com/mampfes/ha_epex_spot/assets/65073191/3d987619-eaa8-4696-acf4-701360a1fa47)
