### ISSUE TITLE
Not seeing TOMORROW's data ?!

### ISSUE THREAD

**Issue by iz3man** [mampfes/ha_epex_spot#134]
Any idea what could go wrong, as I'm not seeing tomorrow's data. I'm pretty sure it once was available. Can't really say what changed.
Data source is smartenergy.at

![image](https://github.com/mampfes/ha_epex_spot/assets/11553674/cfd8b80b-dbb6-4edc-8135-256e49f02cd7)

And this is the apex card's code (basically from the docs with some slight changes):

```
type: custom:apexcharts-card
experimental:
  color_threshold: true
header:
  show: true
  title: ct/kWh
graph_span: 32h
apex_config:
  legend:
    show: false
span:
  start: day
now:
  show: true
  label: Now
yaxis:
  - min: -15
    max: 40
    decimals: 0
    apex_config:
      tickAmount: 4
series:
  - entity: sensor.epex_spot_data_net_price
    name: Strompreis ct/kWh
    type: line
    show:
      extremas: true
    unit: ct/kWh
    data_generator: >
      return entity.attributes.data.map((entry, index) => { return [new
      Date(entry.start_time).getTime(), entry.price_ct_per_kwh]; });
    color_threshold:
      - value: 40
        color: '#ff0000'
      - value: 30
        color: '#facb23'
      - value: 20
        color: '#ffff00'
      - value: 0
        color: '#00ff00'
  - entity: sensor.epex_spot_data_price
    name: Strompreis ct/kWh
    type: column
    extend_to: end
    show:
      extremas: true
    unit: ct/kWh
    data_generator: >
      return entity.attributes.data.map((entry, index) => { return [new
      Date(entry.start_time).getTime(), entry.price_ct_per_kwh]; });
    color_threshold:
      - value: 20
        color: '#ff0000'
      - value: 15
        color: '#facb23'
      - value: 8
        color: '#ffff00'
      - value: 0
        color: '#00ff00'

```
