### ISSUE TITLE
Scale in graph Web scraper is wrong 

### ISSUE THREAD

**Issue by Matze-aaa** [mampfes/ha_epex_spot#164]
See Screenshots.
With SMARD Integration everything is well.
Same settings.

**Comment by Matze-aaa** [comment]
![2smard](https://github.com/user-attachments/assets/3fe2f3a4-b5e9-447e-8c66-8ac5f318604e)

**Comment by suaveolent** [comment]
You are right, thanks. I get the same result. However, I have not yet found out why. The input data seems to be okay.

**Comment by suaveolent** [comment]
I think I figured it out: 

SMARD also includes the prices from previous days. Since EPEX Spot price has been very high on 2024-11-27 (`price_per_kwh: 0.600367)` you see the bigger space, even though the data is not displayed.

**Comment by suaveolent** [comment]
I see. Let me check that. Might be related to apex charts though.

**Comment by suaveolent** [comment]
@Matze-aaa 

You can try it with 
```
yaxis:
  - id: Price
    decimals: 2
    apex_config:
      title:
        text: €/kWh
      tickAmount: 5
```
