### ISSUE TITLE
Find Highest Price region in the future

### ISSUE THREAD

**Issue by Adminius** [mampfes/ha_epex_spot#77]
Hi, I'm trying to iplement battery charge at night and discharge only on few hours a day at the highest price (because of charge/discharge losses it doe'sn make sense to use the battery whole day)

So for this I'm looking for lowest price (1h duration is enough for me):
```
- trigger:
      - platform: time_pattern
        hours: "15"
    action:
      - service: epex_spot.get_lowest_price_interval
        data:
          earliest_start: "14:00:00"
          latest_end: "13:59:00"
          duration:
            hours: 1
            minutes: 0
        response_variable: resp
    sensor:
      - name: Lowest energy price
        device_class: timestamp
        state: "{{ resp.start is defined and resp.start }}"
```

Then two "highest prices"
```
- trigger:
      - platform: time_pattern
        hours: "15"
    action:
      - service: epex_spot.get_highest_price_interval
        data:
          earliest_start: "00:00:00"
          latest_end: "11:59:00"
          duration:
            hours: 3
            minutes: 0
        response_variable: resp
    sensor:
      - name: Highest energy price 1
        device_class: timestamp
        state: "{{ resp.start is defined and resp.start }}"
```
```
  - trigger:
      - platform: time_pattern
        hours: "15"
    action:
      - service: epex_spot.get_highest_price_interval
        data:
          earliest_start: "12:00:00"
          latest_end: "23:59:00"
          duration:
            hours: 3
            minutes: 0
        response_variable: resp
    sensor:
      - name: Highest energy price 2
        device_class: timestamp
        state: "{{ resp.start is defined and resp.start }}"
```
epex_spot_data_net_price:
```
state_class: measurement
data: 
- start_time: '2023-12-21T23:00:00+00:00'
  end_time: '2023-12-22T00:00:00+00:00'
  price_ct_per_kwh: 15.542589999999999
- start_time: '2023-12-22T00:00:00+00:00'
  end_time: '2023-12-22T01:00:00+00:00'
  price_ct_per_kwh: 15.5295
- start_time: '2023-12-22T01:00:00+00:00'
  end_time: '2023-12-22T02:00:00+00:00'
  price_ct_per_kwh: 15.53307
- start_time: '2023-12-22T02:00:00+00:00'
  end_time: '2023-12-22T03:00:00+00:00'
  price_ct_per_kwh: 15.519979999999999
- start_time: '2023-12-22T03:00:00+00:00'
  end_time: '2023-12-22T04:00:00+00:00'
  price_ct_per_kwh: 15.51165
- start_time: '2023-12-22T04:00:00+00:00'
  end_time: '2023-12-22T05:00:00+00:00'
  price_ct_per_kwh: 15.531880000000001
- start_time: '2023-12-22T05:00:00+00:00'
  end_time: '2023-12-22T06:00:00+00:00'
  price_ct_per_kwh: 15.637789999999999
- start_time: '2023-12-22T06:00:00+00:00'
  end_time: '2023-12-22T07:00:00+00:00'
  price_ct_per_kwh: 19.311320000000002
- start_time: '2023-12-22T07:00:00+00:00'
  end_time: '2023-12-22T08:00:00+00:00'
  price_ct_per_kwh: 20.269270000000002
- start_time: '2023-12-22T08:00:00+00:00'
  end_time: '2023-12-22T09:00:00+00:00'
  price_ct_per_kwh: 19.78256
- start_time: '2023-12-22T09:00:00+00:00'
  end_time: '2023-12-22T10:00:00+00:00'
  price_ct_per_kwh: 18.68895
- start_time: '2023-12-22T10:00:00+00:00'
  end_time: '2023-12-22T11:00:00+00:00'
  price_ct_per_kwh: 18.66277
- start_time: '2023-12-22T11:00:00+00:00'
  end_time: '2023-12-22T12:00:00+00:00'
  price_ct_per_kwh: 18.722269999999998
- start_time: '2023-12-22T12:00:00+00:00'
  end_time: '2023-12-22T13:00:00+00:00'
  price_ct_per_kwh: 18.5521
- start_time: '2023-12-22T13:00:00+00:00'
  end_time: '2023-12-22T14:00:00+00:00'
  price_ct_per_kwh: 18.975740000000002
- start_time: '2023-12-22T14:00:00+00:00'
  end_time: '2023-12-22T15:00:00+00:00'
  price_ct_per_kwh: 19.60763
- start_time: '2023-12-22T15:00:00+00:00'
  end_time: '2023-12-22T16:00:00+00:00'
  price_ct_per_kwh: 20.58819
- start_time: '2023-12-22T16:00:00+00:00'
  end_time: '2023-12-22T17:00:00+00:00'
  price_ct_per_kwh: 20.652449999999998
- start_time: '2023-12-22T17:00:00+00:00'
  end_time: '2023-12-22T18:00:00+00:00'
  price_ct_per_kwh: 21.53424
- start_time: '2023-12-22T18:00:00+00:00'
  end_time: '2023-12-22T19:00:00+00:00'
  price_ct_per_kwh: 20.35971
- start_time: '2023-12-22T19:00:00+00:00'
  end_time: '2023-12-22T20:00:00+00:00'
  price_ct_per_kwh: 18.475939999999998
- start_time: '2023-12-22T20:00:00+00:00'
  end_time: '2023-12-22T21:00:00+00:00'
  price_ct_per_kwh: 18.579469999999997
- start_time: '2023-12-22T21:00:00+00:00'
  end_time: '2023-12-22T22:00:00+00:00'
  price_ct_per_kwh: 19.160189999999997
- start_time: '2023-12-22T22:00:00+00:00'
  end_time: '2023-12-22T23:00:00+00:00'
  price_ct_per_kwh: 16.9694
- start_time: '2023-12-22T23:00:00+00:00'
  end_time: '2023-12-23T00:00:00+00:00'
  price_ct_per_kwh: 15.546159999999999
- start_time: '2023-12-23T00:00:00+00:00'
  end_time: '2023-12-23T01:00:00+00:00'
  price_ct_per_kwh: 15.54021
- start_time: '2023-12-23T01:00:00+00:00'
  end_time: '2023-12-23T02:00:00+00:00'
  price_ct_per_kwh: 15.54021
- start_time: '2023-12-23T02:00:00+00:00'
  end_time: '2023-12-23T03:00:00+00:00'
  price_ct_per_kwh: 15.539019999999999
- start_time: '2023-12-23T03:00:00+00:00'
  end_time: '2023-12-23T04:00:00+00:00'
  price_ct_per_kwh: 15.54021
- start_time: '2023-12-23T04:00:00+00:00'
  end_time: '2023-12-23T05:00:00+00:00'
  price_ct_per_kwh: 15.5414
- start_time: '2023-12-23T05:00:00+00:00'
  end_time: '2023-12-23T06:00:00+00:00'
  price_ct_per_kwh: 15.5533
- start_time: '2023-12-23T06:00:00+00:00'
  end_time: '2023-12-23T07:00:00+00:00'
  price_ct_per_kwh: 16.42557
- start_time: '2023-12-23T07:00:00+00:00'
  end_time: '2023-12-23T08:00:00+00:00'
  price_ct_per_kwh: 17.9214
- start_time: '2023-12-23T08:00:00+00:00'
  end_time: '2023-12-23T09:00:00+00:00'
  price_ct_per_kwh: 20.54892
- start_time: '2023-12-23T09:00:00+00:00'
  end_time: '2023-12-23T10:00:00+00:00'
  price_ct_per_kwh: 20.49656
- start_time: '2023-12-23T10:00:00+00:00'
  end_time: '2023-12-23T11:00:00+00:00'
  price_ct_per_kwh: 21.0035
- start_time: '2023-12-23T11:00:00+00:00'
  end_time: '2023-12-23T12:00:00+00:00'
  price_ct_per_kwh: 21.177239999999998
- start_time: '2023-12-23T12:00:00+00:00'
  end_time: '2023-12-23T13:00:00+00:00'
  price_ct_per_kwh: 21.46879
- start_time: '2023-12-23T13:00:00+00:00'
  end_time: '2023-12-23T14:00:00+00:00'
  price_ct_per_kwh: 21.765099999999997
- start_time: '2023-12-23T14:00:00+00:00'
  end_time: '2023-12-23T15:00:00+00:00'
  price_ct_per_kwh: 21.94003
- start_time: '2023-12-23T15:00:00+00:00'
  end_time: '2023-12-23T16:00:00+00:00'
  price_ct_per_kwh: 22.449350000000003
- start_time: '2023-12-23T16:00:00+00:00'
  end_time: '2023-12-23T17:00:00+00:00'
  price_ct_per_kwh: 23.647679999999998
- start_time: '2023-12-23T17:00:00+00:00'
  end_time: '2023-12-23T18:00:00+00:00'
  price_ct_per_kwh: 23.44895
- start_time: '2023-12-23T18:00:00+00:00'
  end_time: '2023-12-23T19:00:00+00:00'
  price_ct_per_kwh: 22.86585
- start_time: '2023-12-23T19:00:00+00:00'
  end_time: '2023-12-23T20:00:00+00:00'
  price_ct_per_kwh: 21.9317
- start_time: '2023-12-23T20:00:00+00:00'
  end_time: '2023-12-23T21:00:00+00:00'
  price_ct_per_kwh: 20.48704
- start_time: '2023-12-23T21:00:00+00:00'
  end_time: '2023-12-23T22:00:00+00:00'
  price_ct_per_kwh: 17.95591
- start_time: '2023-12-23T22:00:00+00:00'
  end_time: '2023-12-23T23:00:00+00:00'
  price_ct_per_kwh: 16.46246

unit_of_measurement: ct/kWh
icon: mdi:currency-eur
friendly_name: Aktueller Strompreis
```
![image](https://github.com/mampfes/ha_epex_spot/assets/17052262/18c52c58-24dd-47cc-b3b2-d5a157c5b2f4)

Now, my expectain is:
Lowest price in the future: 
```
- start_time: '2023-12-23T02:00:00+00:00'
  end_time: '2023-12-23T03:00:00+00:00'
  price_ct_per_kwh: 15.539019999999999
```
-> OK
![image](https://github.com/mampfes/ha_epex_spot/assets/17052262/4b158b8a-22c1-4b58-b272-6a6c244b34be)

But the first highes Price shows me the time in the past:
![image](https://github.com/mampfes/ha_epex_spot/assets/17052262/dcf6faf1-69f1-44d7-9d9d-1a63a7c80625)
Screenshot was made on 22.12 at 15:30
How can I achieve, that my Highest Price 1 will look in the future and will get 3h on 23th?
```
- start_time: '2023-12-23T09:00:00+00:00'
  end_time: '2023-12-23T10:00:00+00:00'
  price_ct_per_kwh: 20.49656
- start_time: '2023-12-23T10:00:00+00:00'
  end_time: '2023-12-23T11:00:00+00:00'
  price_ct_per_kwh: 21.0035
- start_time: '2023-12-23T11:00:00+00:00'
  end_time: '2023-12-23T12:00:00+00:00'
  price_ct_per_kwh: 21.177239999999998
```
